version: '3'
services:
  database:
    container_name: database
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: event